In [1]:
import numpy as np
import torch

In [4]:
W = np.random.rand(4,5).astype(np.float32)
b = np.random.rand(1, 5).astype(np.float32)

x_1 = np.random.rand(1, 4).astype(np.float32)

pred_1 = x_1 @ W + b
print(pred_1, end="\n\n")

l_1 = np.sum(pred_1)
print(l_1)

dL = 1
dpred = dL * np.ones_like(pred_1)

db = np.sum(dpred, axis=0, keepdims=True)
dW = x_1.T @ dpred
dx = dpred @ W.T

print(dW, db)

[[2.1034613  0.83734876 1.4044012  1.2572688  1.0547417 ]]

6.657222
[[0.18930726 0.18930726 0.18930726 0.18930726 0.18930726]
 [0.9330776  0.9330776  0.9330776  0.9330776  0.9330776 ]
 [0.7950942  0.7950942  0.7950942  0.7950942  0.7950942 ]
 [0.00771419 0.00771419 0.00771419 0.00771419 0.00771419]] [[1. 1. 1. 1. 1.]]


In [7]:
linear = torch.nn.Linear(4, 5)
linear.weight = torch.nn.Parameter(torch.tensor(W.T))
linear.bias = torch.nn.Parameter(torch.tensor(b, dtype=torch.float32))

x_2 = torch.tensor(x_1, dtype=torch.float32, requires_grad=True)

pred_2 = linear(x_2)
print(pred_2.detach().numpy(), end="\n\n")
l = torch.sum(pred_2)
l.backward()

print(linear.weight.grad)


[[2.1034613  0.83734876 1.4044013  1.2572688  1.0547417 ]]

tensor([[0.1893, 0.9331, 0.7951, 0.0077],
        [0.1893, 0.9331, 0.7951, 0.0077],
        [0.1893, 0.9331, 0.7951, 0.0077],
        [0.1893, 0.9331, 0.7951, 0.0077],
        [0.1893, 0.9331, 0.7951, 0.0077]])


In [11]:
W1 = np.random.rand(784, 128).astype(np.float32)
b1 = np.random.rand(1, 128).astype(np.float32)

W2 = np.random.rand(128, 10).astype(np.float32)
b2 = np.random.rand(1,10).astype(np.float32)

X = np.random.rand(16, 784).astype(np.float32)

out1 = X @ W1 + b1
out = out1 @ W2 + b2

dout = np.ones_like(out)
db2 = np.sum(dout, axis=0, keepdims=True)
dw2 = out1.T @ dout

dout1 = dout@ W2.T
db1 = np.sum(dout1, axis=0, keepdims=True)
dw1 = X.T @ dout1