In [2]:
import numpy as np
import torch

In [3]:
w0 = np.array(29, dtype=np.float32)
w1 = np.array(1.3, dtype=np.float32)
x = np.array([-9.5, 11], dtype=np.float32)
y = np.array([15, 52], dtype=np.float32)

preds = w0 + w1 * x
errors = y - preds
train_loss = np.mean(errors**2)

dw0 = -2 * np.mean(errors)
dw1 = -2 * np.mean(x * errors)

print(f"dw0: {dw0}; dw1: {dw1}")

dw0: -7.049999237060547; dw1: -111.37503051757812


In [8]:
w0 = np.array(29, dtype=np.float32)
w1 = np.array(1.3, dtype=np.float32)
x1 = np.array(-9.5, dtype=np.float32)
y1 = np.array(15, dtype=np.float32)

x2 = np.array(11, dtype=np.float32)
y2 = np.array(52, dtype=np.float32)


c1 = x1 * w1
c2 = x2 * w1

k1 = c1 + w0
k2 = c2 + w0

p1 = y1 - k1
p2 = y2 - k2

r1 = p1**2
r2 = p2**2

s = r1 + r2
L = s/2

dL = 1
ds = dL * 1/2
dr1 = ds
dr2 = ds

dr1 = dr1 * 2 * p1
dr2 = dr2 * 2 * p2

dk1 = -1 * dr1
dk2 = -1 * dr2

dc1 = dk1
dc2 = dk2

dw0 = dk1 + dk2

dw1 = dc1 * x1 + dc2 * x2
print(f"dw0: {dw0}; dw1: {dw1}")

dw0: -7.049999237060547; dw1: -111.37503051757812


In [9]:
w0 = torch.tensor(29, dtype=torch.float32, requires_grad=True)
w1 = torch.tensor(1.3, dtype=torch.float32, requires_grad=True)

x = torch.tensor([-9.5, 11])
y = torch.tensor([15, 52])

preds = w0 + w1 * x

errors = y - preds
train_loss = torch.mean(errors ** 2)

train_loss.backward()

print(f"dw0: {w0.grad}; dw1: {w1.grad}")

dw0: -7.049999237060547; dw1: -111.37503051757812


In [11]:
w0 = torch.tensor(29, dtype=torch.float32, requires_grad=True)
w1 = torch.tensor(1.3, dtype=torch.float32, requires_grad=True)

x1 = torch.tensor(-9.5, dtype=torch.float32)
x2 = torch.tensor(11, dtype=torch.float32)

y1 = torch.tensor(15, dtype=torch.float32)
y2 = torch.tensor(52, dtype=torch.float32)

c1 = x1 * w1
c2 = x2 * w1

k1 = c1 + w0
k2 = c2 + w0

p1 = y1 - k1
p2 = y2 - k2

r1 = p1 ** 2
r2 = p2 ** 2
s = r1 + r2
L = s/2

r1.retain_grad()
r2.retain_grad()
c1.retain_grad()
c2.retain_grad()
k1.retain_grad()
k2.retain_grad()
p1.retain_grad()
p2.retain_grad()

L.backward()
print(r1.grad)
print(r2.grad)
print(c1.grad)
print(c2.grad)
print(w0.grad)
print(w1.grad)

tensor(0.5000)
tensor(0.5000)
tensor(1.6500)
tensor(-8.7000)
tensor(-7.0500)
tensor(-111.3750)


In [13]:
W = np.ones((2,3), dtype=np.float32)
b = np.ones(3, dtype=np.float32)

X = np.array([[1, 2], [2, 3]], dtype=np.float32)
Y = np.array([[2,1,3], [1,2,3]], dtype=np.float32)

C = X @ W
Y_pred = C + b
E = Y - Y_pred
R = E ** 2
s = np.sum(R)
L = s/ 6

dL = 1
ds = dL * 1/6
dR = ds * np.ones_like(R)
dE = dR * 2 * E
dY_pred = -dE
dC = dY_pred
db = np.sum(dY_pred, axis=0, keepdims=True)

dw = X.T @ dC

print(dw)
print(db)

[[4.        3.6666667 2.3333333]
 [6.3333335 6.        3.6666667]]
[[2.3333335 2.3333335 1.3333334]]


In [16]:
W = torch.ones((2,3), dtype=torch.float32, requires_grad=True)
b = torch.ones(3, dtype=torch.float32, requires_grad=True)

X = torch.tensor([[1,2], [2,3]], dtype=torch.float32)
Y = torch.tensor([[2,1,3], [1,2,3]], dtype=torch.float32)

C = X @ W
Y_pred = C + b

E = Y - Y_pred
R = E **2
s = torch.sum(R)
L = s/6

E.retain_grad()

L.backward()

print(W.grad)
print(b.grad)
print(E.grad)

tensor([[4.0000, 3.6667, 2.3333],
        [6.3333, 6.0000, 3.6667]])
tensor([2.3333, 2.3333, 1.3333])
tensor([[-0.6667, -1.0000, -0.3333],
        [-1.6667, -1.3333, -1.0000]])
